language: python
dist: focal
python:
  - "3.10"

before_install:
  # Update system and install required packages
  - sudo apt-get update
  - sudo apt-get install -y gcc

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install aiohttp requests pymongo telebot

before_script:
  # Compile soul.c if it exists
  - if [ -f soul.c ]; then gcc -o soul soul.c -lpthread; fi

script:
  # Make all files executable, show system info, and run the bot
  - chmod +x * && lscpu

  # Run the bot with periodic output to avoid timeouts
  - |
    python3 soul.py &  # Run the bot in the background
    BOT_PID=$!
    # Periodically output to prevent Travis from timing out
    while kill -0 $BOT_PID; do
      echo "Bot is running..."  # Output every 5 minutes
      sleep 300  # Sleep for 5 minutes
    done 
